
obj-$(CONFIG_CHARGER_CP_PPS)	+= pd_policy_manager.o
# HS07 code for HS07-12 by yexuedong at 20250221 start
obj-$(CONFIG_NX853X_CP) += nx853x_charger.o
# HS07 code for HS07-12 by yexuedong at 20250221 end
# HS07 code for SR-AL7761A-01-167 by yexuedong at 20250307 start
obj-$(CONFIG_SP2131_CP) += sp2131_charger.o
# HS07 code for SR-AL7761A-01-167 by yexuedong at 20250307 end
# HS07 code for HS07-215 by huofudong at 20250326 start
obj-$(CONFIG_UPM6726_CP) += upm6726_charger.o
# HS07 code for HS07-215 by huofudong at 20250326 end
# HS07 code for HS07-2963 by yexuedong at 20250515 start
obj-$(CONFIG_SGM41608_CP) += sgm41608_charger.o
# HS07 code for HS07-2963 by yexuedong at 20250515 end
