# HS07 code for HS07-955 by hehaoran at 20250418 start
ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(srctree)/drivers/gpu/drm/mediatek/mediatek_v2/
# HS07 code for HS07-955 by hehaoran at 20250418 end
obj-$(CONFIG_FINGERPRINT_JIIOV) := jiiov_fp.o
jiiov_fp-objs  := jiiov_platform.o jiiov_netlink.o custom.o
