# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_HS07_SUPPORT)  += fingerprint_sysfs.o
# HS07 code for SR-AL7761A-01-172 by hehaoran at 20250317 start
obj-$(CONFIG_FINGERPRINT_GOODIX) += goodix/
# HS07 code for SR-AL7761A-01-172 by hehaoran at 20250317 end
# HS07 code for SR-AL7761A-01-185 by hehaoran at 20250311 start
obj-$(CONFIG_FINGERPRINT_JIIOV) += jiiov/
# HS07 code for SR-AL7761A-01-185 by hehaoran at 20250311 end
# HS07 code for SR-AL7761A-01-518 by yuli at 20250315 start
obj-$(CONFIG_SILEAD_FP) += silead/
# HS07 code for SR-AL7761A-01-518 by yuli at 20250315 end
obj-$(CONFIG_FINGERPRINT_FOCALTECH) += focaltech/
