obj-$(CONFIG_INPUT_SAR) += sensor_fac_node.o

obj-$(CONFIG_INPUT_SAR) += sensor_user_node.o
obj-$(CONFIG_INPUT_SAR) += sensors_core.o

obj-$(CONFIG_SAR_SX9378)  += sx9378/
obj-$(CONFIG_SAR_HX9031)  += hx9031as/
