obj-$(CONFIG_HPERF_ENABLE) += hperf.o

# HST11 code for AX7800A-1996 by wangletian at 20250613 start 
hperf-objs := hperf_main.o hfreq.o hmem.o hpinfo.o
# HST11 code for AX7800A-1996 by wangletian at 20250613 end 
